FROM python:3.7-alpine

ARG APP_USER="app"
ARG APP_USER_UID="1000"
ARG APP_USER_GROUP="app"
ARG APP_USER_GROUP_GID="1000"

RUN apk --no-cache add make

RUN addgroup -g $APP_USER_GROUP_GID -S $APP_USER_GROUP && adduser -u $APP_USER_UID -S $APP_USER -G $APP_USER_GROUP 

USER $APP_USER

WORKDIR /app

COPY requirements.txt Makefile /app/

RUN make requirements